### ISSUE TITLE
Attempting to run this up locally, is there an API anywhere?

### ISSUE THREAD

**Issue by mmcvittie** [lowtekn7/sotdl-rcg-ui#8]
Hi, I know this hasn't been active for a while but I'm hoping you'll see this. I've been assisting a friend to try and get this running locally as he's hoping to use it to generate some characters for a campaign. He can get the ux running up but we're missing the api. Is the code for it anywhere that could be run up locally as well? Or am I missing something obvious within the main code base?

I'm assured that this is the best SotDL generator there ever was, so if we could run it up locally that would be very useful!

**Comment by JRandall0308** [comment]
I'm the friend referenced above. :)

I was able to get the project built in node.js . When I start it, I get the UI rendered (yay!) but there are Console errors like the following, no matter what localhost port I use.

Failed to load resource: net::ERR_CONNECTION_REFUSED
:5000/paths:1 


       Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost/:1 Uncaught (in promise) AxiosError
localhost/:1 Uncaught (in promise) AxiosError
:5000/characters/0/any/any/any/any:1 


       Failed to load resource: net::ERR_CONNECTION_REFUSED
:5000/characters/0/any/any/any/any:1 


       Failed to load resource: net::ERR_CONNECTION_REFUSED
:5000/characters/0/any/any/any/any:1

**Comment by lowtekn7** [comment]
@JRandall0308 As you don't have a connection to the API, those errors are expected.  The UI expects to have a server to connect to.

@mmcvittie I've added you as a contributor to the archived API repository.  You're welcome to clone it and try to get it working, though the project hasn't been maintained and there are likely hurdles to figure out.

Good luck :)
